"""setup_inicial_com_cascade

Revision ID: 165e549961eb
Revises: 
Create Date: 2026-04-14 16:05:43.982476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '165e549961eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_imagens',
    sa.Column('Categoria', sa.String(length=100), nullable=False),
    sa.Column('Link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('Categoria')
    )
    op.create_table('consumidores',
    sa.Column('id_consumidor', sa.String(length=32), nullable=False),
    sa.Column('prefixo_cep', sa.String(length=10), nullable=False),
    sa.Column('nome_consumidor', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id_consumidor')
    )
    op.create_table('vendedores',
    sa.Column('id_vendedor', sa.String(length=32), nullable=False),
    sa.Column('nome_vendedor', sa.String(length=255), nullable=False),
    sa.Column('prefixo_cep', sa.String(length=10), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id_vendedor')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.String(length=32), nullable=False),
    sa.Column('id_consumidor', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pedido_compra_timestamp', sa.DateTime(), nullable=True),
    sa.Column('pedido_entregue_timestamp', sa.DateTime(), nullable=True),
    sa.Column('data_estimada_entrega', sa.Date(), nullable=True),
    sa.Column('tempo_entrega_dias', sa.Float(), nullable=True),
    sa.Column('tempo_entrega_estimado_dias', sa.Float(), nullable=True),
    sa.Column('diferenca_entrega_dias', sa.Float(), nullable=True),
    sa.Column('entrega_no_prazo', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_consumidor'], ['consumidores.id_consumidor'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('produtos',
    sa.Column('id_produto', sa.String(length=32), nullable=False),
    sa.Column('nome_produto', sa.String(length=255), nullable=False),
    sa.Column('categoria_produto', sa.String(length=100), nullable=True),
    sa.Column('peso_produto_gramas', sa.Float(), nullable=True),
    sa.Column('comprimento_centimetros', sa.Float(), nullable=True),
    sa.Column('altura_centimetros', sa.Float(), nullable=True),
    sa.Column('largura_centimetros', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_produto'], ['categoria_imagens.Categoria'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('avaliacoes_pedidos',
    sa.Column('id_avaliacao', sa.String(length=32), nullable=False),
    sa.Column('id_pedido', sa.String(length=32), nullable=False),
    sa.Column('avaliacao', sa.Integer(), nullable=False),
    sa.Column('titulo_comentario', sa.String(length=255), nullable=True),
    sa.Column('comentario', sa.String(length=1000), nullable=True),
    sa.Column('data_comentario', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    with op.batch_alter_table('avaliacoes_pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_pedidos_id_pedido'), ['id_pedido'], unique=False)

    op.create_table('itens_pedidos',
    sa.Column('id_pedido', sa.String(length=32), nullable=False),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.String(length=32), nullable=False),
    sa.Column('id_vendedor', sa.String(length=32), nullable=False),
    sa.Column('preco_BRL', sa.Float(), nullable=False),
    sa.Column('preco_frete', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id_produto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vendedor'], ['vendedores.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_pedido', 'id_item')
    )
    with op.batch_alter_table('itens_pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedidos_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedidos_id_produto'), ['id_produto'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedidos_id_produto'))
        batch_op.drop_index(batch_op.f('ix_itens_pedidos_id_pedido'))

    op.drop_table('itens_pedidos')
    with op.batch_alter_table('avaliacoes_pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_pedidos_id_pedido'))

    op.drop_table('avaliacoes_pedidos')
    op.drop_table('produtos')
    op.drop_table('pedidos')
    op.drop_table('vendedores')
    op.drop_table('consumidores')
    op.drop_table('categoria_imagens')
    # ### end Alembic commands ###
